// GENERATED by tools from docs/g1/model_summary.json (training/g1/make_model.py). Do not edit by hand.
namespace PoRace {

/// <summary>Unitree G1 contract: 29 position-controlled joints, 500 Hz physics, 50 Hz control (decimation 10).
/// Joint order = qpos[7:], qvel[6:], ctrl, action and observation slices.</summary>
public static class G1Spec {
  public const int Nu = 29;
  public const float SimDt = 0.002f;
  public const int Decimation = 10;
  public const float ActionScale = 0.5f;
  public const int ObsDim = 103;   // linvel 3, gyro 3, gravity 3, command 3, q - default 29, qvel 29, last action 29, phase cos/sin 4
  public const double Mass = 33.341142;
  public const float GaitHz = 1.375f;   // training samples U(1.25, 1.5) per episode
  public static readonly string[] Joints = { "left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint", "left_knee_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint", "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint", "right_knee_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint", "waist_yaw_joint", "waist_roll_joint", "waist_pitch_joint", "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint", "left_elbow_joint", "left_wrist_roll_joint", "left_wrist_pitch_joint", "left_wrist_yaw_joint", "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint", "right_elbow_joint", "right_wrist_roll_joint", "right_wrist_pitch_joint", "right_wrist_yaw_joint" };
  public static readonly float[] DefaultPose = { -0.312f, 0f, 0f, 0.669f, -0.363f, 0f, -0.312f, 0f, 0f, 0.669f, -0.363f, 0f, 0f, 0f, 0.073f, 0.2f, 0.2f, 0f, 0.6f, 0f, 0f, 0f, 0.2f, -0.2f, 0f, 0.6f, 0f, 0f, 0f };
  public static readonly float[] InitQpos = { 0f, 0f, 0.755f, 1f, 0f, 0f, 0f, -0.312f, 0f, 0f, 0.669f, -0.363f, 0f, -0.312f, 0f, 0f, 0.669f, -0.363f, 0f, 0f, 0f, 0.073f, 0.2f, 0.2f, 0f, 0.6f, 0f, 0f, 0f, 0.2f, -0.2f, 0f, 0.6f, 0f, 0f, 0f };
  public static readonly float[] Kp = { 75f, 75f, 75f, 75f, 20f, 2f, 75f, 75f, 75f, 75f, 20f, 2f, 75f, 75f, 75f, 75f, 75f, 75f, 75f, 2f, 2f, 2f, 75f, 75f, 75f, 75f, 2f, 2f, 2f };
  public static readonly float[] Damping = { 2f, 2f, 2f, 2f, 1f, 0.2f, 2f, 2f, 2f, 2f, 1f, 0.2f, 2f, 2f, 2f, 2f, 2f, 2f, 2f, 0.2f, 0.2f, 0.2f, 2f, 2f, 2f, 2f, 0.2f, 0.2f, 0.2f };
  public static readonly float[] ForceMax = { 88f, 139f, 88f, 139f, 50f, 50f, 88f, 139f, 88f, 139f, 50f, 50f, 88f, 50f, 50f, 25f, 25f, 25f, 25f, 25f, 5f, 5f, 25f, 25f, 25f, 25f, 25f, 5f, 5f };
}

}
